apps/users/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from apps.users.views import *

urlpatterns = [
    url(r'^login', user_login, name="login"),
    url(r'^salir/$', LogOut, name = 'logout'),
    url(r'^signup', user_signup, name="signup"),
    url(r'^reset', user_recuperar, name="reset"),
    url(r'^resec', user_resetear, name='resetear'),
	url(r'^resepc/(?P<code>\w+)/', reset_pass),
    url(r'^confirm/', reset_confirm),
    url(r'^perfil/', user_perfil),
	url(r'^modificarUsuario/', modificarUsuario, name='modificarUsuario'),
    url(r'^crear_cuenta/', registrar_usuario, name='registrar_usuario'),
]

proyectoSem/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from apps.users.views import *
from apps.portal.views import *
from views import validacion
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('apps.users.urls', namespace="users_app")),
    url(r'^portal/', include('apps.portal.urls', namespace="portal_app")),
    url(r'^localidades/', include('apps.localizacion.urls', namespace="locacalizacion_app")),
    url(r'^maps/', include('apps.geolocalizacion.urls', namespace="geolocalizacion_app")),
    url(r'^sensores/', include('apps.sensores.urls', namespace="sensores_app")),
    url(r'^$', pag_principal),
]
if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
)

apps/users/models.py
# -*- coding: utf-8 -*-
from django.db import models
import datetime
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.timezone import now

# Create your models here.

class UserManager(BaseUserManager, models.Manager):

    def _create_user(self, username, email, us_nombre,us_apellidos,
                us_telefono_movil, password, is_staff,is_superuser,is_active, **extra_fields):

        email = self.normalize_email(email)
        if not email:
            raise ValueError('El email debe ser obligatorio')
        user = self.model(username = username, email=email, us_nombre=us_nombre,
                        us_apellidos=us_apellidos, us_telefono_movil=us_telefono_movil, is_active=is_active, is_staff = is_staff, is_superuser = is_superuser, **extra_fields)
        user.set_password(password)
        user.save( using = self._db)
        return user

    def create_user(self, username, email, us_nombre, us_apellidos, us_telefono_movil, password=None, **extra_fields):
        return self._create_user(username, email, us_nombre, us_apellidos, us_telefono_movil, password, False, False,False, **extra_fields)

    def create_superuser(self, username, email, password=None, **extra_fields):
        return self._create_user(username, email,'none','none','none',password, True, True,True, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(max_length=100, unique=True,verbose_name="Username",
                                help_text='Debe ser único, sin espacios ni caracteres especiales.')
    us_nombre = models.CharField(max_length=100,verbose_name="Nombres",
                                help_text='Nombres del usuario.')
    us_apellidos = models.CharField(max_length=100,verbose_name="Apellidos",
                                    help_text='Apellidos del usuario.')
    us_telefono_movil = models.CharField(max_length=10,verbose_name="Telefono",
                                        help_text='Telefono o movil del usuario.')
    us_avatar = models.ImageField(upload_to = 'users', null=True,blank=True,verbose_name="Avatar")
    email = models.EmailField(unique=True,verbose_name="Email",
                                help_text='Cuenta de mail del usuario, debe ser unica.')

    objects = UserManager()

    is_active = models.BooleanField(default = True,
                                    help_text='Designa si el usuario debe ser tratado como activo.')
    is_staff = models.BooleanField(default = False,
                                    help_text='Indica si el usuario puede iniciar sesión en el sitio de administracíon.')

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return self.us_nombre+' '+self.us_apellidos

    class Meta:
        verbose_name_plural=u'Usuarios'


class UserProfile(models.Model):
    user = models.ForeignKey(User)
    activation_key = models.CharField(max_length=40, blank=True)
    key_expires = models.DateTimeField(default=datetime.date.today())

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural=u'Perfiles de Usuario'

apps/users/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
import hashlib, datetime, random
from django.http import JsonResponse
from django.core.mail import send_mail
from .models import User, UserProfile
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect,get_object_or_404,render_to_response
from django.template.loader import render_to_string
from django.utils import timezone
from django.contrib.auth.decorators import login_required
import os
from django.contrib.auth import logout
import json

# Create your views here.
def user_login(request):
    if not request.user.is_authenticated():
        if request.method == "POST":
            user = request.POST['username']
            cont = request.POST['pwd']
            dic = LogIn(request, user,cont)
            if dic['msg'] is 'ok':
                messages.add_message(request, messages.SUCCESS, 'Bienvenido '+user)
            else:
                messages.add_message(request, messages.ERROR, dic['result'])
            return redirect('/')
        else:
            return render(request, 'users/logearse.html')
    else:
        return  redirect("/")

def LogIn(request, username, password):
	user = authenticate(username = username, password = password)
	if user is not None:
		if user.is_active:
			login(request, user)
			dic = {'msg' : 'ok'}
		else:
			dic = {'msg' : 'noActivo', 'result' : 'La cuenta con la que intenta ingresar no esta activada.'}
	else:
		dic = {'msg' : 'noExiste', 'result' : 'La cuenta con la que intenta ingresar no existe.'}
	return dic

def user_signup(request):
    if not request.user.is_authenticated():
        return render(request, 'users/registrarse.html')
    else:
        return redirect("/")


def user_recuperar(request):
    if not request.user.is_authenticated():
        return render(request, 'users/recuperar.html')
    else:
        return redirect("/")

def LogOut(request):
    logout(request)
    return redirect('/')

def user_resetear(request):
    dic = {}
    if request.method == "POST":
        try:
            emailUs = request.POST['email']
            user=User.objects.filter(email=emailUs)
            if user.exists():
                salt = hashlib.sha1(str(random.random())).hexdigest()[:5]
                activation_key = hashlib.sha1(salt+emailUs).hexdigest()
                key_expires = datetime.datetime.today() + datetime.timedelta(2)

                find_user=User.objects.get(email=emailUs)
                # Crear el perfil del usuario
                new_profile = UserProfile(user=find_user, activation_key=activation_key,key_expires=key_expires)
                new_profile.save()

                # Enviar un email de confirmación
                # contexto

                ctx = {
                    'usuario' : user,
                    'code' : activation_key
                }

                asunto = 'Restablecer contrasena'
                msg_plain = render_to_string('template_emails/resetear_cont/index.txt', ctx)
                msg_html = render_to_string('template_emails/resetear_cont/index.html', ctx)
                find_empresa = 'bxbr8792@gmail.com'

                # Enviar un email de confirmación
                send_mail(
                    asunto,
                    msg_plain,
                    find_empresa,
                    [emailUs],
                    html_message=msg_html,
                )
                dic = {'msg':'ok'}
            else:
                dic = {'msg':'No existe un usuario con ese email'}
                print 'No existe un usuario con ese email'
        except Exception, e:
            dic = {'msg':e}
            print e
    response = JsonResponse(dic)
    return HttpResponse(response.content)

def reset_pass(request, code):
    if request.user.is_authenticated():
        HttpResponseRedirect('/')

    # Verifica que el token de activación sea válido y sino retorna un 404
    user_profile = get_object_or_404(UserProfile, activation_key=code)

    # verifica si el token de activación ha expirado y si es así renderiza el html de registro expirado
    if user_profile.key_expires < timezone.now():
        return render_to_response('users/expirado.html')

    dic = {
        'code' : code
    }
    return render_to_response('users/reestablecer.html',dic)



def reset_confirm(request):
    if request.is_ajax():

        try:
            print request.POST
            find_user_profile = UserProfile.objects.get(activation_key = request.POST['code'])
            find_user = find_user_profile.user
            find_user.set_password(request.POST['contrasenia'])
            find_user.save()

            dic = {'msg' : 'ok'}

            find_user_profile.delete()

        except Exception, e:
            print e
            dic = {'msg' : 'err'}

        response = JsonResponse(dic)
        return HttpResponse(response.content)

    else:
        HttpResponseRedirect('/')

@login_required(login_url='/')
def user_perfil(request):
    return render(request, 'users/perfil.html')

def modificarUsuario(request):
    datos = {}
    usuario = request.POST.get('username')
    # contrasena = request.POST.get('contrasena')
    nombre = request.POST.get('nombre')
    apellido = request.POST.get('apellido')
    email = request.POST.get('email')
    telefono = request.POST.get('telefono')
    avatar = request.FILES.get('id_avatar_usuario')

    mensaje ="El registro ha sido creado correctamente"

    try:
        usuario = User.objects.get(id=request.user.id)
        # usuario.username = usuario
        # usuario.password = contrasena
        usuario.us_nombre = nombre
        usuario.us_apellidos = apellido
        usuario.us_telefono_movil = telefono
        usuario.email = email
        if avatar:
            if usuario.us_avatar:
                os.remove(usuario.us_avatar.path)
            usuario.us_avatar = avatar

        mensaje = "El registro ha sido actualizado correctamente"
        usuario.save()

        datos['message'] = mensaje
        datos['result'] = "OK"
    except Exception as e:
        print(e)
        datos['message'] = "Ha ocurrido un error al tratar de ingresar el registro. COD.: "+str(e.message)
        datos['result'] = "X"

    return HttpResponse(json.dumps(datos), content_type="application/json")

def registrar_usuario(request):
    datos = {}
    if request.method == "POST" and request.is_ajax():
        try:
            listaRegistrados = User.objects.all()

            for l in listaRegistrados:
                if l.username == request.POST['reg_usuario']:
                    datos['message'] = "Ya existe un usuario con ese nombre."
                    datos['result'] = "X"
                    return HttpResponse(json.dumps(datos), content_type="application/json")

                if l.email == request.POST['reg_email']:
                    datos['message'] = "Ya existe un usuario con ese correo."
                    datos['result'] = "X"
                    return HttpResponse(json.dumps(datos), content_type="application/json")

            User.objects.create_user(username=request.POST['reg_usuario'],
                                     email=request.POST['reg_email'],
                                     us_nombre=request.POST['reg_nombre'],
                                     us_apellidos=request.POST['reg_apellido'],
                                     us_telefono_movil=request.POST['reg_telefono'],
                                     password=request.POST['reg_pass1'])

            user = authenticate(username=request.POST['reg_usuario'], password=request.POST['reg_pass1'])
            login(request, user)

            messages.add_message(request, messages.SUCCESS, 'Bienvenido ' + request.POST['reg_usuario'] )
            datos['result'] = "OK"
        except Exception, e:
            datos['message'] = "Ha ocurrido un error al tratar de crear la cuenta. COD.: " + str(e.message)
            datos['result'] = "X"

        return HttpResponse(json.dumps(datos), content_type="application/json")

    return render(request, 'users/registrarse.html')

apps/users/templates/users/logearse.html
{% load staticfiles %}
<!doctype html>
<html class="fixed">

<head>

	<!-- Basic -->
	<meta charset="UTF-8">
    <title>Inicio de sesión</title>

	<meta name="keywords" content="HTML5 Admin Template" />
	<meta name="description" content="Porto Admin - Responsive HTML5 Template">
	<meta name="author" content="okler.net">

	<!-- Mobile Metas -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

	<!-- Web Fonts  -->
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

	<!-- Vendor CSS -->
	<link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.css' %}" />

	<link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/font-awesome.css' %}" />
	<link rel="stylesheet" href="{% static 'assets/vendor/magnific-popup/magnific-popup.css' %}" />
	<link rel="stylesheet" href="{% static 'assets/vendor/bootstrap-datepicker/css/datepicker3.css' %}" />

	<!-- Theme CSS -->
	<link rel="stylesheet" href="{% static 'assets/stylesheets/theme.css' %}" />

	<!-- Skin CSS -->
	<link rel="stylesheet" href="{% static 'assets/stylesheets/skins/default.css' %}" />

	<!-- Theme Custom CSS -->
	<link rel="stylesheet" href="{% static 'assets/stylesheets/theme-custom.css' %}">

	<link rel="stylesheet" href="{% static 'assets/stylesheets/toastr.min.css' %}">

	<!-- Head Libs -->
	<script src="{% static 'assets/vendor/modernizr/modernizr.js' %}"></script>
</head>

<body>
	<!-- start: page -->
	<section class="body-sign">
		<div class="center-sign">
			<a href="/" class="logo pull-left">
				<img src="{% static 'assets/images/logos.png' %}" height="54" alt="Smart City" />
			</a>
			<form method="post">{% csrf_token %}
				<div class="panel panel-sign">
					<div class="panel-title-sign mt-xl text-right">
						<h2 class="title text-uppercase text-weight-bold m-none"><i class="fa fa-user mr-xs"></i> Sign In</h2>
					</div>
					<div class="panel-body">
						<form action="index.html" method="post">
							<div class="form-group mb-lg">
								<label>Username</label>
								<div class="input-group input-group-icon">
									<input name="username" type="text" class="form-control input-lg" required />
									<span class="input-group-addon">
											<span class="icon icon-lg">
												<i class="fa fa-user"></i>
											</span>
									</span>
								</div>
							</div>

							<div class="form-group mb-lg">
								<div class="clearfix">
									<label class="pull-left">Password</label>
									<a href="{% url 'users_app:reset' %}" class="pull-right">Olvide mi contraseña</a>
								</div>
								<div class="input-group input-group-icon">
									<input name="pwd" type="password" class="form-control input-lg" required />
									<span class="input-group-addon">
											<span class="icon icon-lg">
												<i class="fa fa-lock"></i>
											</span>
									</span>
								</div>
							</div>

							<div class="row">
								<div class="col-sm-8">
									<div class="checkbox-custom checkbox-default">
										<input id="RememberMe" name="rememberme" type="checkbox" />
										
									</div>
								</div>
								<div class="col-sm-4 text-right">
									<button type="submit" class="btn btn-primary hidden-xs">Sign In</button>
									<button type="submit" class="btn btn-primary btn-block btn-lg visible-xs mt-lg">Sign In</button>
								</div>
							</div>

							<span class="mt-lg mb-lg line-thru text-center text-uppercase">
									<span>O</span>
							</span>

							

							<p class="text-center">No tiene cuenta? <a href="{% url 'users_app:signup' %}">Registrarse!</a>

						</form>
					</div>
				</div>
			</form>

			<p class="text-center text-muted mt-md mb-md">&copy; Copyright 2016. All Rights Reserved.</p>
		</div>
	</section>
	<!-- end: page -->

	<!-- Vendor -->
	<script src="{% static 'assets/vendor/jquery/jquery.js' %}"></script>
	<script src="{% static 'assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.js' %}"></script>
	<script src="{% static 'assets/vendor/nanoscroller/nanoscroller.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
	<script src="{% static 'assets/vendor/magnific-popup/magnific-popup.js' %}"></script>
	<script src="{% static 'assets/vendor/jquery-placeholder/jquery.placeholder.js' %}"></script>

	<!-- Theme Base, Components and Settings -->
	<script src="{% static 'assets/javascripts/theme.js' %}"></script>

	<!-- Theme Custom -->
	<script src="{% static 'assets/javascripts/theme.custom.js' %}"></script>

	<!-- Theme Initialization Files -->
	<script src="{% static 'assets/javascripts/theme.init.js' %}"></script>
	<script src="{% static 'assets/javascripts/toastr.min.js' %}"></script>
	<script type="text/javascript">
	document.onload = inicio();
	function inicio() {
			{% if messages %}
					{% for msg in messages %}
							{% if msg.tags == 'success' %}
									toastr.options={"progressBar": true}
									toastr.success('{{ msg }}','Info')
							{% else %}
									{% if msg.tags == 'warning' %}
											toastr.options={"progressBar": true ,"showDuration": "500", "hideDuration": "3000", "timeOut": "10000","extendedTimeOut": "3000"}
											toastr.warning('{{ msg }}','Info')
									{% else %}
											toastr.options={"progressBar": true}
											toastr.error('{{ msg }}','Info')
									{% endif %}
							{% endif %}
					{% endfor %}
			{% endif %}
	}
	</script>

</body>

</html>

apps/users/templates/users/perfil.html
{% extends "base.html" %}
{% load staticfiles %}
    {% block css %}
    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="{% static 'assets/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/vendor/morris/morris.css' %}" />
    {% endblock css %}
    <!-- start: page -->
    {% block content %}
    <header class="page-header">
    <h2>Mi perfil</h2>

    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="/">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Perfil</span></li>
        </ol>

        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
    </div>
</header>
                <div class="row">
                        <div class="col-md-12">
                            <form role="form" enctype="multipart/form-data" id="formularioModificar" name="formularioModificar" class="form-horizontal" onsubmit="return false;" method="post">{% csrf_token %}
                                <section class="panel">
                                    <header class="panel-heading">
                                        <div class="panel-actions">
                                            <a href="#" class="panel-action panel-action-toggle" data-panel-toggle></a>
                                            <a href="#" class="panel-action panel-action-dismiss" data-panel-dismiss></a>
                                        </div>

                                        <h2 class="panel-title">Mi perfil</h2>
                                        <p class="panel-subtitle">
                                            Puede actualizar los datos en el siguiente formulario!!
                                        </p>
                                    </header>
                                    <div class="panel-body">
                                        <div class="validation-message">
                                            <ul></ul>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label">Nombre de Usuario <span class="required"></span></label>
                                            <div class="col-sm-9">
                                                <input type="text" name="username" class="form-control" title="Por favor ingrese nombre de usuario." placeholder="{{user.username}}" value="{{user.username}}" disabled="true" />
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label">Nombre <span class="required">*</span></label>
                                            <div class="col-sm-9">
                                                <input type="text" name="nombre" class="form-control" title="Por favor ingrese nombre." placeholder="{{user.us_nombre}}" value="{{user.us_nombre}}" required/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label">Apellidos<span class="required">*</span></label>
                                            <div class="col-sm-9">
                                                <input type="text" name="apellido" class="form-control" title="Por favor ingrese ellidos." placeholder="{{user.us_apellidos}}" value="{{user.us_apellidos}}" required/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label">Telefono<span class="required">*</span></label>
                                            <div class="col-sm-9">
                                                <input type="text" name="telefono" class="form-control" title="Por favor ingrese telefono." placeholder="{{user.us_telefono_movil}}" value="{{user.us_telefono_movil}}" required/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label">Avatar<span class="required">*</span></label>
                                            <div class="col-sm-9">
                                                <input id="id_avatar_usuario" name="id_avatar_usuario" class="file" accept="image/*" type="file">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-3 control-label">Email<span class="required">*</span></label>
                                            <div class="col-sm-9">
                                                <input type="text" name="email" class="form-control" title="Por favor ingrese email." placeholder="{{user.email}}" value="{{user.email}}" required/>
                                            </div>
                                        </div>
                                    </div>
                                    <footer class="panel-footer">
                                        <div class="row">
                                            <div class="col-sm-9 col-sm-offset-3">
                                                <button type="submit" onclick="usuario_modificar('{% url "users_app:modificarUsuario" %}')" id="btn_modificar" class="btn btn-primary">Submit</button>
                                            </div>
                                        </div>
                                    </footer>
                                </section>
                            </form>
                        </div>
                    </div>
    {% endblock content %}
    <!-- end: page -->
    {% block js %}
    <!-- Specific Page Vendor -->
        <script src="{% static 'assets/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js' %}"></script>
        <!-- Specific Page Vendor -->
        <script src="{% static 'assets/vendor/jquery-validation/jquery.validate.js' %}"></script>
        <!-- Examples -->
        <script src="{% static 'assets/javascripts/forms/examples.validation.js' %}"></script>
        <!--Users -->
        <script src="{% static 'js/users.js' %}"></script>
    {% endblock js %}

apps/users/templates/users/registrarse.html
{% load staticfiles %}
<!doctype html>
<html class="fixed">
	<head>

		<!-- Basic -->
		<meta charset="UTF-8">
        <title>Crear una cuenta</title>

		<meta name="keywords" content="HTML5 Admin Template" />
		<meta name="description" content="Porto Admin - Responsive HTML5 Template">
		<meta name="author" content="okler.net">

		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

		<!-- Vendor CSS -->
		<link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.css' %}" />

		<link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/font-awesome.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/vendor/magnific-popup/magnific-popup.css' %}" />
		<link rel="stylesheet" href="{% static 'assets/vendor/bootstrap-datepicker/css/datepicker3.css' %}" />

		<!-- Theme CSS -->
		<link rel="stylesheet" href="{% static 'assets/stylesheets/theme.css' %}" />

		<!-- Skin CSS -->
		<link rel="stylesheet" href="{% static 'assets/stylesheets/skins/default.css' %}" />

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="{% static 'assets/stylesheets/theme-custom.css' %}">
        <link rel="stylesheet" href="{% static 'assets/stylesheets/toastr.min.css' %}">

		<!-- Head Libs -->
		<script src="{% static 'assets/vendor/modernizr/modernizr.js' %}"></script>
	</head>
	<body>
		<!-- start: page -->
		<section class="body-sign">
			<div class="center-sign">
				<a href="/" class="logo pull-left">
					<img src="{% static 'assets/images/logos.png' %}" height="54" alt="Smart City" />
				</a>

				<div class="panel panel-sign">
					<div class="panel-title-sign mt-xl text-right">
						<h2 class="title text-uppercase text-weight-bold m-none"><i class="fa fa-user mr-xs"></i> Registrarse</h2>
					</div>
					<div class="panel-body">
						<form id="form_registrar" name="form_registrar" onsubmit="return false;" enctype="multipart/form-data" method="POST">{% csrf_token %}
							<div class="form-group mb-lg">
								<label>Nombre</label>
								<input id="reg_nombre" name="reg_nombre" maxlength="100" type="text" class="form-control input-md" required />
							</div>

							<div class="form-group mb-lg">
								<label>Apellidos</label>
								<input id="reg_apellido" name="reg_apellido" maxlength="100" type="text" class="form-control input-md" required />
							</div>

                            <div class="form-group mb-lg">
								<label>Nombre de usuario</label>
								<input id="reg_usuario" name="reg_usuario" maxlength="100" type="text" class="form-control input-md" required />
							</div>

                            <div class="form-group mb-lg">
								<label>Teléfono</label>
								<input id="reg_telefono" name="reg_telefono" maxlength="10" type="text" class="form-control input-md" />
							</div>

                            <div class="form-group mb-lg">
								<label>Correo electrónico</label>
								<input id="reg_email" name="reg_email" type="email" class="form-control input-md" required />
							</div>

							<div class="form-group mb-none">
								<div class="row">
									<div class="col-sm-6 mb-lg">
										<label>Contraseña</label>
										<input id="reg_pass1" name="reg_pass1" type="password" class="form-control input-md" />
									</div>
									<div class="col-sm-6 mb-lg">
										<label>Confirmar contraseña</label>
										<input id="reg_pass2" name="reg_pass2" type="password" class="form-control input-md" />
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-sm-4 pull-right">
									<button onclick="registrarUsuario()" type="button" id="btnRegistrar" class="btn btn-primary hidden-xs">Crear cuenta</button>
								</div>
							</div>

                            <hr>
							<p class="text-center">¿Ya posee una cuenta? <a href="{% url 'users_app:login' %}">Iniciar sesión</a>
                                <br>

						</form>
					</div>
				</div>

				<p class="text-center text-muted mt-md mb-md">&copy; Copyright 2016. All Rights Reserved.</p>
			</div>
		</section>
		<!-- end: page -->

		<!-- Vendor -->
		<script src="{% static 'assets/vendor/jquery/jquery.js' %}"></script>
        <script src="{% static 'assets/vendor/jquery-validation/jquery.validate.js' %}"></script>
		<script src="{% static 'assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js' %}"></script>
		<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.js' %}"></script>
		<script src="{% static 'assets/vendor/nanoscroller/nanoscroller.js' %}"></script>
		<script src="{% static 'assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
		<script src="{% static 'assets/vendor/magnific-popup/magnific-popup.js' %}"></script>
		<script src="{% static 'assets/vendor/jquery-placeholder/jquery.placeholder.js' %}"></script>
        <script src="{% static 'js/users.js' %}"></script>
        <script src="{% static 'assets/javascripts/toastr.min.js' %}"></script>

		<!-- Theme Base, Components and Settings -->
		<script src="{% static 'assets/javascripts/theme.js' %}"></script>

		<!-- Theme Custom -->
		<script src="{% static 'assets/javascripts/theme.custom.js' %}"></script>

		<!-- Theme Initialization Files -->
		<script src="{% static 'assets/javascripts/theme.init.js' %}"></script>

	</body>
</html>